server:
  port: 8193
  context-path: /

# 服务节点,要求分布式下每个节点不同
node: 01

spring:

  dubbo:
    application:
      name: xxpay-manage
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: org.xxpay.manage
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    settings:
      number_format: 0.##
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 10Mb
  jackson:
    serialization:
      INDENT_OUTPUT: true
  profiles:
     active: prod

# JWT
jwt:
  cookie: XxPay_Mgr_Token
  secret: XxpPayGood
  expiration: 604800 # 7天
  mchSecret: XxpPayGood

logging:
  file: ./log/xxpay-manage.log

config:
  mchQrUrl: http://127.0.0.1:8191/payment/qrcode
  downMchBillUrl: http://localhost:8195/mch_bill_down
  loginMchUrl: http://127.0.0.1:8191/x_mch/start/index.html#/user/mgr_login/mchId=%s/token=%s
  loginAgentUrl: http://127.0.0.1:8192/x_agent/start/index.html#/user/mgr_login/agentId=%s/token=%s
  settNotifyUrl: http://127.0.0.1:8193/api/notify/sett
  payUrl: http://127.0.0.1:3020/api
