server:
  port: 8194

spring:
  dubbo:
    application:
      name: xxpay-task
    registry:
      address: @zookeeper.url@
    scan: org.xxpay

  mvc:
    static-path-pattern: /mch_bill_down/**
  resources:
    static-locations: file:${config.mchBillPath}

config:
  ali:
    billPath: @bill.root.path@/alipay/
  mchBillPath: @bill.root.path@/mch/

logging:
  file: /var/log/xxpay-task.log
  level:
    root: info
