language: java
sudo: false

jdk:
  - oraclejdk8
cache:
  directories:
  - .autoconf
  - $HOME/.m2

services:
  - docker

before_install:
  - echo "hello install"
install:
  - echo "install"

notifications:
  email:
    recipients:
      - yiming.jin@live.com
      - gaofei2003@gmail.com
    on_success: always
    on_failure: always

jobs:
  include:
    - stage: maven
      script: mvn clean verify

    - stage: 生产环境打包
      script: 
        - export DOCKER_USER=赚钱的大氓
        - export DOCKER_PASS=6snC9AznJpjWZAw
        - export DOCKER_REPO=registry.cn-hongkong.aliyuncs.com
        - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin $DOCKER_REPO
        - python package.py
      if: branch =~ /^(master|release|production|stable).*$/

    - stage: 测试环境打包
      script: 
        - export DOCKER_USER=赚钱的大氓
        - export DOCKER_PASS=6snC9AznJpjWZAw
        - export DOCKER_REPO=registry.cn-shenzhen.aliyuncs.com
        - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin $DOCKER_REPO
        - python package.py
      if: branch =~ /^(dev|test|staging).*$/