image: primetoninc/jdk:1.8

pipelines:
  branches:
    test:
      - step:
          services:
            - docker
          script:
            - yum install -y maven
            - mvn install -Ptest
            - docker login --username 赚钱的大氓 --password 6snC9AznJpjWZAw registry.cn-hongkong.aliyuncs.com
            - python package.py hongkong
    master:
      - step:
          services:
            - docker
          script:
            - yum install -y maven
            - mvn install -P
            #- docker login --username 赚钱的大氓 --password 6snC9AznJpjWZAw registry.cn-hongkong.aliyuncs.com
            #- python package.py prod
    develop:
      - step:
          services:
            - docker
          script:
            - yum install -y maven
            - mvn install 
            - docker login --username 赚钱的大氓 --password 6snC9AznJpjWZAw registry.cn-hongkong.aliyuncs.com
            - python package.py dev
            
definitions:
  services:
    docker:
      memory: 1024