server:
  port: 8194

spring:
  dubbo:
    application:
      name: xxpay-task
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: org.xxpay
  profiles:
     active: prod

  mvc:
    static-path-pattern: /mch_bill_down/**
  resources:
    static-locations: file:${config.mchBillPath}

config:
  ali:
    billPath: /Users/dingzhiwei/Downloads//alipay/
  mchBillPath: /Users/dingzhiwei/Downloads//mch/

logging:
  file: ./log/xxpay-task.log
  level:
    root: info
