version: '2.1'
services:
  mysql:
    image: registry.cn-hongkong.aliyuncs.com/evencc/evenpay-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: evenpay123
      MYSQL_DATABASE: xxpaydb
      MYSQL_USER: evenpay
      MYSQL_PASSWORD: evenpay123
  zookeeper:
    image: 'zookeeper:3.4.9'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server

  activemq:
    image: ivonet/activemq
    ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"
    environment:
      - ACTIVEMQ_MIN_MEMORY=512
      - ACTIVEMQ_MAX_MEMORY=2048
      - ACTIVEMQ_ENABLED_AUTH=false

  service:
    links:
      - "mysql"
      - "zookeeper"
    image: registry.cn-hongkong.aliyuncs.com/evencc/evenpay-service:latest
    ports:
      - "8190:8190"
    restart: always
  mch:
    links:
      - "zookeeper"
      - "pay"
    image: registry.cn-hongkong.aliyuncs.com/evencc/evenpay-merchant:latest
    ports:
      - "8191:8191"
    restart: always

  agent:
    links:
      - "zookeeper"
      - "mch"
      - "pay"
    image: registry.cn-hongkong.aliyuncs.com/evencc/evenpay-agent:latest
    ports:
      - "8192:8192"
    restart: always

  pay:
    depends_on:
      - "zookeeper"
      - "activemq"
      - "redis"
    image: registry.cn-hongkong.aliyuncs.com/evencc/evenpay-pay:latest
    ports:
      - "3020:3020"
    restart: always

  task:
    links:
      - "zookeeper"
    image: registry.cn-hongkong.aliyuncs.com/evencc/evenpay-task:latest
    ports:
      - "8194:8194"
    restart: always

  mgr:
    links:
      - "zookeeper"
      - "mch"
      - "agent"
      - "pay"
    image: registry.cn-hongkong.aliyuncs.com/evencc/evenpay-manage:latest
    ports:
      - "8193:8193"
    restart: always
