version: '2'
services:
  zookeeper:
    image: 'zookeeper:3.4.9'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server

  activemq:
    image: ivonet/activemq
    ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"
    environment:
      - ACTIVEMQ_MIN_MEMORY=512
      - ACTIVEMQ_MAX_MEMORY=2048
      - ACTIVEMQ_ENABLED_AUTH=false

  service:
    links:
      - "zookeeper"
    image: registry.cn-shenzhen.aliyuncs.com/evencc/evenpay-service:mang
    #image: registry.cn-shenzhen.aliyuncs.com/evencc/evenpay-service:mang
    ports:
      - "8190:8190"
    restart: always

  pay:
    depends_on:
      - "service"
    links:
      - "zookeeper"
      - "redis"
      - "activemq"
    #image: registry.cn-shenzhen.aliyuncs.com/evencc/evenpay-pay:mang
    image: registry.cn-shenzhen.aliyuncs.com/evencc/evenpay-pay:mang
    command: ["./wait.sh", "-t", "120", "service:8190", "--", "sh", "entry.sh"]
    ports:
      - "3020:3020"
    restart: always

  mgr:
    depends_on:
      - "service"
    links:
      - "zookeeper"
      - "mch"
      - "agent"
      - "pay"
    image: registry.cn-shenzhen.aliyuncs.com/evencc/evenpay-manage:mang
    command: ["./wait.sh", "-t", "120", "service:8190", "--", "sh", "entry.sh"]
    ports:
      - "8193:8193"
    restart: always

  agent:
    depends_on:
      - "service"
    links:
      - "zookeeper"
      - "mch"
      - "pay"
    image: registry.cn-shenzhen.aliyuncs.com/evencc/evenpay-agent:mang
    command: ["./wait.sh", "-t", "120", "service:8190", "--", "sh", "entry.sh"]
    ports:
      - "8192:8192"
    restart: always


  mch:
    depends_on:
      - "service"
    links:
      - "zookeeper"
      - "pay"
    image: registry.cn-shenzhen.aliyuncs.com/evencc/evenpay-merchant:mang
    command: ["./wait.sh", "-t", "120", "service:8190", "--", "sh", "entry.sh"]
    ports:
      - "8191:8191"
    restart: always

  task:
    depends_on:
      - "service"
    links:
      - "zookeeper"
    image: registry.cn-shenzhen.aliyuncs.com/evencc/evenpay-task:mang
    command: ["./wait.sh", "-t", "120", "service:8190", "--", "sh", "entry.sh"]
    ports:
      - "8194:8194"
    restart: always
