server:
  port: 8193
  context-path: /

# 服务节点,要求分布式下每个节点不同
node: 01

spring:

  dubbo:
    application:
      name: xxpay-manage
    registry:
      #address: zookeeper://zookeeper:2181
      address: @zookeeper.url@
    scan: org.xxpay.manage
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    settings:
      number_format: 0.##
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 10Mb
  jackson:
    serialization:
      INDENT_OUTPUT: true

# JWT
jwt:
  cookie: XxPay_Mgr_Token
  secret: XxpPayGood
  expiration: 604800 # 7天
  mchSecret: XxpPayGood

logging:
  file: ./log/xxpay-manage.log

config:
  mchQrUrl: @mch.site.url@/payment/qrcode
  downMchBillUrl: @reconciliation.site.url@/mch_bill_down
  loginMchUrl: @mch.site.url@/x_mch/start/index.html#/user/mgr_login/mchId=%s/token=%s
  loginAgentUrl: @agent.site.url@/x_agent/start/index.html#/user/mgr_login/agentId=%s/token=%s
  settNotifyUrl: @mgr.site.url@/api/notify/sett
  payUrl: @pay.site.url@/api
