server:
  port: 3020

# 服务节点,要求分布式下每个节点不同
node: 01

spring:
  dubbo:
    application:
      name: xxpay-pay
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20881
    scan: org.xxpay.pay
  redis:
    #host: 127.0.0.1
    host: localhost
    #password: 
    password: ''
    #port: 6379
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  activemq:
    broker-url: failover:(tcp://127.0.0.1:61616?wireFormat.maxInactivityDuration=0)
    in-memory: false
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30000  # 空闲的连接过期时间，默认为30秒
      expiry-timeout: 0 # 强制的连接过期时间，与idleTimeout的区别在于：idleTimeout是在连接空闲一段时间失效，而expiryTimeout不管当前连接的情况，只要达到指定时间就失效。默认为0，never
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    settings:
      number_format: 0.##

logging:
  file: ./log/xxpay-pay.log

config:
  notifyUrl: http://127.0.0.1:3020/notify/%s/notify_res.htm
  returnUrl: http://127.0.0.1:3020/notify/%s/return_res.htm
  notifyTransUrl: http://127.0.0.1:3020/notify/%s/trans_notify.htm
  notifyDivisionUrl: http://127.0.0.1:3020/notify/%s/division_notify.htm
  payUrl: http://127.0.0.1:3020/api
  certRootPath: /Users/dingzhiwei/java/tmp/cert1
  agentpayNotifyUrl: http://127.0.0.1:3020/api/agentpay/notify

task:
  reissue.pay.switch: true
  reissue.pay.ip: 127.0.0.1
  reissue.trans.switch: true
  reissue.trans.ip: 127.0.0.1
  reissue.agentpay.switch: true
  reissue.agentpay.ip: 127.0.0.1
