server:
  port: 8190

# 服务节点,要求分布式下每个节点不同
node: 01

spring:
  dubbo:
    application:
      name: xxpay-service
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
    scan: org.xxpay.service.impl
  profiles:
     active: prod

logging:
  file: ./log/xxpay-service.log
  level:
    org.xxpay.service.dao.mapper: debug