name: evenpay-devops
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v1
        
      - name: build docker images 
        uses: docker://driv/docker-maven-java-oracle
        run: |
          echo "6snC9AznJpjWZAw" | docker login -u "赚钱的大氓" --password-stdin registry.cn-hongkong.aliyuncs.com
          python package.py
