name: evenpay-build
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: build docker images 
        run: |
          echo "6snC9AznJpjWZAw" | docker login -u "赚钱的大氓" --password-stdin registry.cn-hongkong.aliyuncs.com
          python action_build.py
